### PR TITLE
Bump to 2.34.2, add aarch64 support and add myself as maintainer

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@ryanvolz This one is ready for a merge.

Many thanks!

**Comment by ryanvolz** [comment]
The updates look good, but I noticed in the build log that `dbus` is missing as a runtime dependency in the built package on aarch64 despite the fact that its run_exports should be automatically adding it as with the other arches. Maybe the `dbus` package is broken? I'll go inspect its metadata.

**Comment by tschoonj** [comment]
Yeah I also have been seeing some weird stuff with `dbus` this morning

Shall I just add it to the run deps?

**Comment by tschoonj** [comment]
For example, I did an aarch64 build of gtk3, and noticed that dbus was not pulled in. I had to add it as an explicit dependency for the meson step to succeed.

**Comment by ryanvolz** [comment]
Sure, it looks the the run_exports wants it to be pinned like `{{ pin_compatible('dbus') }}`. Add a comment that we had to do this manually so we can remember to clean it up when that's possible.

**Comment by tschoonj** [comment]
Actually, this recipe has no run section at all. That just seems wrong. I put in the packages whose shared libraries are used.

**Comment by ryanvolz** [comment]
> Actually, this recipe has no run section at all. That just seems wrong. I put in the packages whose shared libraries are used.

Those aren't necessary when the package in 'host' has a run_exports section and it's working properly. Unless the package has different requirements, it's better to rely on the run_exports so that pins are set correctly. In this case, the package does have all of the correct run dependencies except for `dbus`, so the best thing to do is to have only `{{ pin_compatible('dbus') }}` in the run section.

**Comment by tschoonj** [comment]
Thanks!

**Comment by tschoonj** [comment]
Thanks!

**Comment by ryanvolz** [comment]
Thank *you*!

**Comment by ryanvolz** [comment]
> The updates look good, but I noticed in the build log that `dbus` is missing as a runtime dependency in the built package on aarch64 despite the fact that its run_exports should be automatically adding it as with the other arches. Maybe the `dbus` package is broken? I'll go inspect its metadata.

The `dbus` package on Anaconda Cloud is indeed missing the `info/run_exports.json` on linux-aarch64 and linux-ppc64le that would tell downstream packages to add the run dependency.

**Pull request merged**
